name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Run Docker SQL
      run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=YourStrong@Passw0rd" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest
      
    - name: Run sqlclient
      run: sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -d tempdb -Q "SELECT @@version;"
      
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o devops-package
      env:  
        CONNECTIONSTRINGS__DATABASE: "Server=localhost;Database=DevOpsChallenge.SalesApi;User Id=sa;Password=YourStrong@Passw0rd;"
    
    - name: run background
      run: ./devops-package/DevOpsChallenge.SalesApi &
      env:  
        CONNECTIONSTRINGS__DATABASE: "Server=localhost;Database=DevOpsChallenge.SalesApi;User Id=sa;Password=YourStrong@Passw0rd;"

    - name: Curl Test
      run: curl -v http://localhost:5000/api/sales
      
    - name: Test
      run: sleep 10 && dotnet test /home/runner/work/devops-challenge-dotnet/devops-challenge-dotnet/DevOpsChallenge.SalesApi.sln --verbosity normal
      env:
        SALES_API_ENDPOINT: http://localhost:5000/api/sales
        CONNECTIONSTRINGS__DATABASE: "Server=localhost;Database=DevOpsChallenge.SalesApi;User Id=sa;Password=YourStrong@Passw0rd;"

#    - name: Sample test
#      run: ls -al ./devops-package
#  unit-tests:
#    runs-on: ubuntu-latest
#    needs:
#      - build
#    steps:

